# Bazel file for fastrpc
# Two modules to be exported - fastrpc, cdsp-loader

package(
    default_visibility = [
        "//visibility:public",
    ],
)

load(":define_modules.bzl", "define_modules", "define_vm_modules", "define_target_modules")

define_modules("pineapple", "consolidate", "no")

define_modules("pineapple", "gki", "no")

define_modules("blair", "consolidate", "no")

define_modules("blair", "gki", "no")

define_modules("sun", "consolidate", "no")

define_modules("sun", "perf", "no")

define_vm_modules("sun-tuivm", "debug-defconfig")
define_vm_modules("sun-oemvm", "debug-defconfig")

define_vm_modules("sun-tuivm", "defconfig")
define_vm_modules("sun-oemvm", "defconfig")

define_vm_modules("canoe-tuivm", "debug-defconfig")
define_vm_modules("canoe-oemvm", "debug-defconfig")

define_vm_modules("canoe-tuivm", "defconfig")
define_vm_modules("canoe-oemvm", "defconfig")

define_vm_modules("art-tuivm", "debug-defconfig")
define_vm_modules("art-oemvm", "debug-defconfig")

define_vm_modules("art-tuivm", "defconfig")
define_vm_modules("art-oemvm", "defconfig")

define_modules("tuna", "consolidate", "no")

define_modules("tuna", "perf", "no")

define_modules("kera", "consolidate", "no")

define_modules("kera", "perf", "no")

define_modules("niobe", "consolidate", "no")

define_modules("niobe", "gki", "no")

define_modules("monaco", "consolidate", "no")

define_modules("monaco", "gki", "no")

define_modules("monaco", "perf", "no")

define_modules("parrot", "consolidate", "no")

define_modules("parrot", "perf", "no")

define_modules("canoe", "perf", "no")

define_modules("canoe", "consolidate", "no")

define_modules("seraph", "consolidate", "yes")

define_modules("seraph", "gki", "yes")

define_modules("seraph", "perf", "yes")

define_modules("vienna", "perf", "no")

define_modules("vienna", "consolidate", "no")

define_modules("alor", "perf", "no")

define_modules("alor", "consolidate", "no")

define_modules("x1p42100", "perf", "no")

define_modules("x1p42100", "consolidate", "no")

define_modules("art", "perf", "no")

define_modules("art", "consolidate", "no")

define_modules("chora", "perf", "no")

define_modules("chora", "consolidate", "no")

define_modules("pebble", "perf", "no")

define_modules("pebble", "consolidate", "no")

define_modules("hamoa", "perf", "no")

define_modules("hamoa", "consolidate", "no")

define_modules("art16k", "perf", "no")

define_modules("art16k", "consolidate", "no")

define_modules("malabar", "consolidate", "no")

define_modules("malabar", "perf", "no")

define_target_modules()

