# Bazel file for fastrpc
# Two modules to be exported - fastrpc, cdsp-loader

package(
    default_visibility = [
        "//visibility:public",
    ],
)

load(":define_modules.bzl", "define_modules")

define_modules("pineapple", "consolidate","no")

define_modules("pineapple", "gki","no")

define_modules("blair", "consolidate","no")

define_modules("blair", "gki","no")

define_modules("sun", "consolidate","no")

define_modules("sun", "perf","no")

define_modules("tuna", "consolidate","no")

define_modules("tuna", "perf","no")

define_modules("kera", "consolidate","no")

define_modules("kera", "perf","no")

define_modules("niobe", "consolidate","no")

define_modules("niobe", "gki","no")

define_modules("monaco", "consolidate","no")

define_modules("monaco", "perf","no")

define_modules("parrot", "consolidate","no")

define_modules("parrot", "gki","no")

define_modules("lahaina", "consolidate", "no")

define_modules("lahaina", "gki", "no")

define_modules("lahaina", "perf", "no")
